import java.util.Arrays;
// Programme of Insertion Sorting.
public class  Main {

    public static void Sorting(int[] array) {
        int n = array.length;
        for (int j = 1; j < n; j++) {
            int k = array[j];
            int i = j-1;
            while ( (i >=0) && ( array [i] > k ) ) {
                array [i+1] = array [i];
                i--;
            }
            array[i+1] = k;
        }
    }
    public static void main(String[] args) {
        int[] arr1 = {9,14,3,2,43,11,58,22};
        System.out.println("Original Array");
        System.out.println(Arrays.toString(arr1));

        Sorting(arr1);
        System.out.println("Sorted Array");
        System.out.println(Arrays.toString(arr1));

    }

}

// Generated by Amena Kureshi